### ISSUE TITLE
[Bug:] Gradle 7: Not Able to build gradle after upgrade to 1.7.6

### ISSUE THREAD

**Issue by automationsky** [boskokg/flutter_blue_plus#446] opened 2023-07-27 17:27 UTC
### FlutterBluePlus Version

1.12.6

### What OS?

Android

### OS Version

Android 13

### What happened?

 i tried upgrading it to latest version. but now i am not able to build the app. 

### Logs

```shell
[+1060 ms] FAILURE: Build failed with an exception.
[   +2 ms] * Where:
[        ] Build file '/Users/mac/Documents/Development/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_blue_plus-1.12.6/android/build.gradle' line: 6
[        ] * What went wrong:
[        ] A problem occurred evaluating project ':flutter_blue_plus'.
[        ] > No signature of method: build_cg5xit1m9kyg7552ircwbwspa.android() is applicable for argument types: (build_cg5xit1m9kyg7552ircwbwspa$_run_closure1) values: [build_cg5xit1m9kyg7552ircwbwspa$_run_closure1@244ec8e2]
[        ] * Try:
[        ] > Run with --stacktrace option to get the stack trace.
[        ] > Run with --info or --debug option to get more log output.
[        ] > Run with --scan to get full insights.
[        ] * Get more help at https://help.gradle.org
[        ] BUILD FAILED in 1s
```

**Comment by jfacoustic** [comment] 2023-07-27 17:52
@automationsky There were some breaking changes to the API. Could you check the output of `flutter analyze`?  You should be getting linting errors and post them?

**Comment by automationsky** [comment] 2023-07-27 18:22
@jfacoustic  please have a look below flutter analyze logs : 


Analyzing smart-filter...                                               

warning • The include file 'package:flutter_lints/flutter.yaml' in '/Users/mac/Documents/Development/smart-filter/analysis_options.yaml' can't be found when analyzing
       '/Users/mac/Documents/Development/smart-filter' • analysis_options.yaml:10:10 • include_file_not_found
   info • The import of 'package:get/get_state_manager/get_state_manager.dart' is unnecessary because all of the used elements are also provided by the import of
          'package:get/state_manager.dart' • lib/controllers/home_page_controller.dart:1:8 • unnecessary_import
   info • The import of 'package:flutter/cupertino.dart' is unnecessary because all of the used elements are also provided by the import of 'package:flutter/material.dart' •
          lib/core/app_button.dart:1:8 • unnecessary_import
   info • This class (or a class that this class inherits from) is marked as '@immutable', but one or more of its instance fields aren't final: AppButton.buttonSubtitle,
          AppButton.isPressed • lib/core/app_button.dart:5:7 • must_be_immutable
   info • Unused import: 'dart:typed_data' • lib/core/app_utils.dart:2:8 • unused_import
   info • 'canLaunch' is deprecated and shouldn't be used. Use canLaunchUrl instead • lib/core/app_utils.dart:76:15 • deprecated_member_use
   info • 'launch' is deprecated and shouldn't be used. Use launchUrl instead • lib/core/app_utils.dart:77:13 • deprecated_member_use
   info • Unused import: 'package:flutter_ble_sample/core/preferences_handler.dart' • lib/core/filter_configuration_validations.dart:2:8 • unused_import
   info • Unused import: 'package:flutter_ble_sample/screens/choose_lang_screen.dart' • lib/main.dart:6:8 • unused_import
   info • Unused import: 'screens/home_page.dart' • lib/main.dart:8:8 • unused_import
   info • The import of 'package:flutter/cupertino.dart' is unnecessary because all of the used elements are also provided by the import of 'package:flutter/material.dart' •
          lib/screens/choose_lang_screen.dart:1:8 • unnecessary_import
   info • This class (or a class that this class inherits from) is marked as '@immutable', but one or more of its instance fields aren't final: CounterScreen.connectedDevice •
          lib/screens/counter_screen.dart:11:7 • must_be_immutable
   info • The value of the local variable 'v1' isn't used • lib/screens/counter_screen.dart:314:27 • unused_local_variable
   info • The value of the local variable 'v3' isn't used • lib/screens/counter_screen.dart:316:27 • unused_local_variable
   info • This class (or a class that this class inherits from) is marked as '@immutable', but one or more of its instance fields aren't final: FilterConfiguration.iosServer •
          lib/screens/filter_configuration.dart:13:7 • must_be_immutable
   info • The operand can't be null, so the condition is always true • lib/screens/filter_configuration.dart:498:63 • unnecessary_null_comparison
   info • The value of the local variable 'v1' isn't used • lib/screens/filter_configuration.dart:1165:15 • unused_local_variable
   info • The value of the local variable 'v3' isn't used • lib/screens/filter_configuration.dart:1167:15 • unused_local_variable
   info • Unused import: 'dart:convert' • lib/screens/filter_discovery_page.dart:2:8 • unused_import
   info • This class (or a class that this class inherits from) is marked as '@immutable', but one or more of its instance fields aren't final: DiscoveryPage.langStrings •
          lib/screens/filter_discovery_page.dart:13:7 • must_be_immutable
   info • This class (or a class that this class inherits from) is marked as '@immutable', but one or more of its instance fields aren't final: FlushingScreen.connectedDevice •
          lib/screens/flushing_screen.dart:15:7 • must_be_immutable
   info • The operand can't be null, so the condition is always true • lib/screens/flushing_screen.dart:514:20 • unnecessary_null_comparison
   info • The value of the local variable 'v1' isn't used • lib/screens/flushing_screen.dart:566:13 • unused_local_variable
   info • The value of the local variable 'v2' isn't used • lib/screens/flushing_screen.dart:567:13 • unused_local_variable
   info • The value of the local variable 'analogThresholdValue' isn't used • lib/screens/flushing_screen.dart:794:14 • unused_local_variable
   info • The exception variable 'e' isn't used, so the 'catch' clause can be removed • lib/screens/flushing_screen.dart:827:27 • unused_catch_clause
   info • Unused import: 'package:flutter_ble_sample/screens/selected_filter_screen.dart' • lib/screens/home_page.dart:9:8 • unused_import
   info • The value of the field '_bluetoothState' isn't used • lib/screens/home_page.dart:24:8 • unused_field
   info • The value of the local variable 'statuses' isn't used • lib/screens/home_page.dart:315:39 • unused_local_variable
   info • 'FlatButton' is deprecated and shouldn't be used. Use TextButton instead. See the migration guide in flutter.dev/go/material-button-migration-guide). This feature was
          deprecated after v1.26.0-18.0.pre. • lib/screens/home_page.dart:375:15 • deprecated_member_use
   info • 'FlatButton.FlatButton' is deprecated and shouldn't be used. Use TextButton instead. See the migration guide in flutter.dev/go/material-button-migration-guide). This
          feature was deprecated after v1.26.0-18.0.pre. • lib/screens/home_page.dart:375:15 • deprecated_member_use
   info • 'FlatButton' is deprecated and shouldn't be used. Use TextButton instead. See the migration guide in flutter.dev/go/material-button-migration-guide). This feature was
          deprecated after v1.26.0-18.0.pre. • lib/screens/home_page.dart:420:15 • deprecated_member_use
   info • 'FlatButton.FlatButton' is deprecated and shouldn't be used. Use TextButton instead. See the migration guide in flutter.dev/go/material-button-migration-guide). This
          feature was deprecated after v1.26.0-18.0.pre. • lib/screens/home_page.dart:420:15 • deprecated_member_use
   info • Unused import: 'filter_configuration.dart' • lib/screens/selected_filter_screen.dart:9:8 • unused_import
   info • The library 'package:flutter_ble_sample/main.dart' is legacy, and shouldn't be imported into a null safe library • test/widget_test.dart:9:8 •
          import_of_legacy_library_into_null_safe

35 issues found. (ran in 3.0s)

**Comment by jfacoustic** [comment] 2023-07-27 19:07
What is the output of `flutter build`?

**Comment by chipweinberger** [comment] 2023-07-27 19:17
I've never seen this before. try

`flutter clean`

**Comment by chipweinberger** [comment] 2023-07-27 19:18
also maybe the changes made in 1.12.1 are breaking you

**Comment by automationsky** [comment] 2023-07-28 04:19
i am able to run the app upto 1.7.5 version only. i tried flutter clean as well.

**Comment by chipweinberger** [comment] 2023-07-28 04:31
are you able to build 11.x, 12.x, etc?

**Comment by automationsky** [comment] 2023-07-28 04:32
also i am getting this error while performing write operation. 

[ERROR:flutter/lib/ui/ui_dart_state.cc(198)] Unhandled Exception: PlatformException(write_characteristic_error, writeCharacteristic failed, null, null)

here is my code for write : 

Future<void> startFlushing() async {
    List<BluetoothService> services =
        await widget.connectedDevice!.discoverServices();

    for (int i = 0; i < services.length; i++) {
      var characteristicLists = services[i].characteristics;

      for (int j = 0; j < characteristicLists.length; j++) {
        BluetoothCharacteristic bluetoothCharacteristic =
            characteristicLists[j];

        if (bluetoothCharacteristic.properties.write == true) {
          try {
            final command = "SF__1\r";
            final convertedCommand = AsciiEncoder().convert(command);
            bluetoothCharacteristic.write(convertedCommand).then((value) {
              setState(() {
                flushingStarted = true;
                print('Flushing started : $flushingStarted');
              });
            });
          } catch (e) {
            print('START FLUSH Exception :$e');
          }
        }
      }
    }
  }

am i doing it right ? is it possible that it is happening due to Bluetooth device issue ?

**Comment by automationsky** [comment] 2023-07-28 04:46
> are you able to build 1.11.x, 1.12.x, etc?

No.  i am able to build until 1.7.5 version only. from 1.7.6 i am getting this error

**Comment by chipweinberger** [comment] 2023-07-28 07:56
read the change log 

we changed gradle to 8

and later we deleted it entirely. 

not sure why this would break you, but try copying the project locally and undoing the gradle changes

**Comment by EmreSURK** [comment] 2023-07-28 13:54
Nope, he is not the only one with this problem, I also have it. I am using the blue_print_pos package and it depends on this package. Spend a couple of days.

FYI: I am using an old version of Flutter to build the project. I use FVM to use the older SDK(sdk: 2.17.6) version. Probably the reason is Flutter's version. 

I just tried v1.10.0 and it seems fine. I am scanning the versions and reading the changelogs to detect the most recent compilable version.

**Comment by automationsky** [comment] 2023-07-28 17:40
> The easiest way to debug issues in FlutterBluePlus is to make your own local copy.
> 
> ```
> cd /user/downloads
> git clone https://github.com/boskokg/flutter_blue_plus.git
> ```
> 
> then in pubspec.yaml add the repo by path:
> 
> ```
>   flutter_blue_plus:
>     path: /user/downloads/flutter_blue_plus
> ```
> 
> Now you can edit the FlutterBluePlus code yourself.

Thanks... will try this

**Comment by EmreSURK** [comment] 2023-07-29 09:07
@automationsky Why you closed the issue, is the problem solved for you? If so, is it possible to share the solution? Thanks.

**Comment by EmreSURK** [comment] 2023-07-30 08:14
FYI: I am using an old version of Flutter with FVM because of some background location dependencies. 
@automationsky İs this same for you? 
Please share your versions so we can double-check. 

```
flutter --version 
Flutter 3.0.5 • channel stable • https://github.com/flutter/flutter.git
Framework • revision f1875d570e (1 year, 1 month ago) • 2022-07-13 11:24:16 -0700
Engine • revision e85ea0e79c
Tools • Dart 2.17.6 • DevTools 2.12.2
```

**Comment by chipweinberger** [comment] 2023-08-01 19:58
The problem is this commit: https://github.com/boskokg/flutter_blue_plus/commit/265104355a8baae427eb98476f1f54d6295de6bd

Gradle 7 does not know how to do 

`namespace 'com.boskokg.flutter_blue_plus_example'`

You will need to upgrade to Gradle 8

**Comment by MrCsabaToth** [comment] 2023-08-04 01:50
If it's about the `namespace` moved from the `AndroidManifest.xml` to the `gradle.build` is how Flutter Community *_plus plugins handle it: it can be in a conditional statement, so instead of:

    namespace 'com.boskokg.flutter_blue_plus'

it'd be:

    // Conditional for compatibility with AGP <4.2.
    if (project.android.hasProperty("namespace")) {
        namespace 'com.boskokg.flutter_blue_plus'
    }

**Comment by chipweinberger** [comment] 2023-08-04 05:20
If someone with Gradle 7 wants to try that -- please open a PR if it works.

We'd need to _undo_ this change too probably

```diff
- <manifest xmlns:android="http://schemas.android.com/apk/res/android" package="com.boskokg.flutter_blue_plus_example">
+ <manifest xmlns:android="http://schemas.android.com/apk/res/android">
```

https://github.com/boskokg/flutter_blue_plus/commit/265104355a8baae427eb98476f1f54d6295de6bd

**Comment by sboicu** [comment] 2023-08-11 10:09
also not working for me. I have upgraded android, flutter, plugins, everything, starting with new project as well. any ideas?

**Comment by chipweinberger** [comment] 2023-09-30 20:19
closing since it seems no one is having problems anymore. 

open a new issue if needed.

**Closed by chipweinberger** 2023-09-30 20:19 UTC
Labels: bug

**Comment by wajipu** [comment] 2023-12-19 11:06
![WechatIMG205](https://github.com/boskokg/flutter_blue_plus/assets/101818388/96e6d1f1-d9e6-4264-b5a6-97643bd06b8b)
Has the problem been solved?

**Comment by chipweinberger** [comment] 2023-12-20 21:30
what version of flutter? 

try `flutter clean`

open a new issue if needed

**Comment by wajipu** [comment] 2023-12-22 06:15
version  Flutter 2.10.5 ,`flutter clean`  I've done it too many times

**Comment by chipweinberger** [comment] 2023-12-22 07:51
Upgrade to flutter 3 will probably fix it

**Comment by wajipu** [comment] 2023-12-22 09:53
Is there no other way? It will be very troublesome for the whole framework to adapt if we upgrade.

**Comment by chipweinberger** [comment] 2023-12-22 09:57
not sure. If you fix it, open a PR.

**Comment by chipweinberger** [comment] 2023-12-22 09:58
try setting this

`<manifest xmlns:android="http://schemas.android.com/apk/res/android" package="com.lib.flutter_blue_plus_example">`

**Comment by chipweinberger** [comment] 2023-12-22 10:02
also, look here https://github.com/boskokg/flutter_blue_plus/commit/265104355a8baae427eb98476f1f54d6295de6bd

maybe you need to add those conditionals

**Comment by chipweinberger** [comment] 2023-12-22 10:04
ie

```
group 'com.lib.flutter_blue_plus'
version '1.0'

apply plugin: 'com.android.library'

android {
    compileSdkVersion 33

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    defaultConfig {
        minSdkVersion 21
    }

    gradle.projectsEvaluated {
        tasks.withType(JavaCompile) {
            options.compilerArgs << "-Xlint:deprecation"
            options.compilerArgs << "-Xlint:unchecked"
        }
    }

    // Conditional for compatibility with AGP <4.2.
    if (project.android.hasProperty("namespace")) {
        namespace 'com.boskokg.flutter_blue_plus_example'
    }
}
```

**Comment by chipweinberger** [comment] 2023-12-22 10:11
it should be fixed on master branch

143309ae20a9caec5bcf0ac981744431cd26f01c

try pointing your pubspec.yaml to master branch

**Comment by wajipu** [comment] 2023-12-22 11:16
Solved how to open pr?

**Comment by wajipu** [comment] 2023-12-22 11:46
![image](https://github.com/boskokg/flutter_blue_plus/assets/101818388/d0df5126-ae78-4981-86f3-cddf9390d254)
`package="com.lib.flutter_blue_plus_example"`
![image](https://github.com/boskokg/flutter_blue_plus/assets/101818388/3445836b-9d91-4bb5-ae74-8d7e7f90238d)
Replacing the entire code solved the problem.

**Comment by wajipu** [comment] 2023-12-22 11:50
"The following error occurs on Android v12.1:
'[ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: PlatformException(startScan, FlutterBluePlus requires android.permission.BLUETOOTH_CONNECT permission, null, null).' Why is this happening?"

**Comment by wajipu** [comment] 2023-12-22 11:54
"The following error occurs on Android v12.1:
'[ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: PlatformException(startScan, FlutterBluePlus requires android.permission.BLUETOOTH_CONNECT permission, null, null).' Why is this happening?"
![image](https://github.com/boskokg/flutter_blue_plus/assets/101818388/86e1740f-2f97-4111-a4a6-8b6ba16c7ac6)。
"Here are my settings."

**Comment by chipweinberger** [comment] 2023-12-22 21:55
@wajipu , open a new issue
