### ISSUE TITLE
writing to characteristic throwing error (I/flutter (18689): Exception: PlatformException(write_characteristic_error, gattServer.writeCharacteristic() returned false, null, null)

### ISSUE THREAD

**Issue by cyclone-pk** [boskokg/flutter_blue_plus#394] opened 2023-07-20 11:58 UTC
after connection I want to write data to characteristic but it thrown error. 
on iOS it is working as expected;
on android it doesn't,t let me write anything.
is there any workaround for it?

**Comment by chipweinberger** [comment] 2023-07-20 12:34
try 1.8.2

it will tell you why it is failing.

**Comment by chipweinberger** [comment] 2023-07-20 12:35
closing as dupe of https://github.com/boskokg/flutter_blue_plus/issues/385

**Closed by chipweinberger** 2023-07-20 12:35 UTC
