### ISSUE TITLE
Write charecters to bluetooth error PlatformException(write_characteristic_error, writeCharacteristic failed, null, null)

### ISSUE THREAD

**Issue by Narayanhegde14** [boskokg/flutter_blue_plus#393] opened 2023-07-20 11:40 UTC
In my app, I was writing to Bluetooth every 300 milliseconds after 30-40 min I started getting this error, when this error started coming, nothing was writing to the Bluetooth device, I tried closing and reopening the app, restarting the Bluetooth and I even tried restarting the mobile. Nothing worked. And at last, after clearing the whole app data it started working again. Any solution?

**Comment by chipweinberger** [comment] 2023-07-20 11:59
Need more details.

**Comment by chipweinberger** [comment] 2023-07-20 12:36
closing as dupe of https://github.com/boskokg/flutter_blue_plus/issues/385

**Closed by chipweinberger** 2023-07-20 12:36 UTC
