### ISSUE TITLE
[Help]: App becomes very slow after calling `startScan` a few times later

### ISSUE THREAD

**Issue by wxxedu** [boskokg/flutter_blue_plus#661] opened 2023-11-07 15:39 UTC
### Requirements

- [X] I've looked at the README 'Common Problems' section

### Have you checked this problem on the example app?

Yes

### FlutterBluePlus Version

1.26.4

### Flutter Version

3.13.9

### What OS?

iOS

### OS Version

iOS 17.0

### Bluetooth Module

N/A

### What is your problem?

The app becomes very slow after startScan is called a few times. I have cancelled the subscription to startScan in my code. 

### Logs

```shell
flutter: [FBP] <setLogLevel> args: 5
flutter: [FBP] <setLogLevel> result: true
flutter: [FBP] [[ OnAdapterStateChanged ]] result: {adapter_state: 4}
flutter: [FBP] <startScan> args: {service_uuids: [], mac_addresses: [], allow_duplicates: true, android_scan_mode: 2, android_uses_fine_location: false}
flutter: [FBP] <startScan> result: true
flutter: 2023-11-07T16:35:34.663890 [INFO][BleDataSourceImpl] Scan started
flutter: 2023-11-07T16:35:34.664310 [INFO][UserBluetoothRepository] Adding subscription: SCANNING
flutter: [FBP] [[ OnScanResponse ]] result: {result: {advertisement_data: {manufacturer_data: {6: 0109202292164520fdcfca147b5444b70f9c61b6851fe316f98849}, service_uuids: null, connectable: 0, service_data: null, local_name: null, tx_power_level: null}, device: {platform_name: null, remote_id: 5074BAE8-31D0-B64F-3115-8EAB33C3F74E}, rssi: -79}}
flutter: [FBP] [[ OnScanResponse ]] result: {result: {advertisement_data: {manufacturer_data: null, service_uuids: null, connectable: 0, service_data: null, local_name: null, tx_power_level: null}, device: {platform_name: null, remote_id: B62FD6B0-4F98-042B-C493-529A37A859A7}, rssi: -77}}
flutter: [FBP] [[ OnScanResponse ]] result: {result: {advertisement_data: {manufacturer_data: null, service_uuids: [5B36D774-8A3E-4401-AFAC-B78A2499ABCA], connectable: 1, service_data: null, local_name: Ket9, tx_power_level: 10}, device: {platform_name: Ket9, remote_id: 45D73EBA-DAEA-6402-925D-D2E9190018A7}, rssi: -64}}
flutter: [FBP] [[ OnScanResponse ]] result: {result: {advertisement_data: {manufacturer_data: {13: 0100000000}, service_uuids: [5B36D774-8A3E-4401-AFAC-B78A2499ABCA], connectable: 1, service_data: null, local_name: Ket9, tx_power_level: 10}, device: {platform_name: Ket9, remote_id: 45D73EBA-DAEA-6402-925D-D2E9190018A7}, rssi: -64}}
flutter: [FBP] [[ OnScanResponse ]] result: {result: {advertisement_data: {manufacturer_data: null, service_uuids: null, connectable: 1, service_data: null, local_name: null, tx_power_level: null}, device: {platform_name: null, remote_id: 12567BDD-4E77-8E39-10A3-8CA5F887D57E}, rssi: -46}}
flutter: [FBP] [[ OnScanResponse ]] result: {result: {advertisement_data: {manufacturer_data: null, service_uuids: null, connectable: 1, service_data: null, local_name: null, tx_power_level: null}, device: {platform_name: null, remote_id: 12567BDD-4E77-8E39-10A3-8CA5F887D57E}, rssi: -45}}
flutter: [FBP] [[ OnScanResponse ]] result: {result: {advertisement_data: {manufacturer_data: null, service_uuids: null, connectable: 0, service_data: null, local_name: null, tx_power_level: null}, device: {platform_name: null, remote_id: B037ABD1-9710-3574-5C52-596061E3A67C}, rssi: -45}}
flutter: [FBP] [[ OnScanResponse ]] result: {result: {advertisement_data: {manufacturer_data: {6: 010f210a769363f6cf344c4150544f502d444b4f5249373431}, service_uuids: null, connectable: 0, service_data: null, local_name: null, tx_power_level: null}, device: {platform_name: null, remote_id: D3363F29-3C45-A429-CD9B-1A57A7C41836}, rssi: -65}}
flutter: [FBP] [[ OnScanResponse ]] result: {result: {advertisement_data: {manufacturer_data: {6: 01092002ad1a7ac9c22470741b48a75efed0b6be9a6fdb01b75715}, service_uuids: null, connectable: 0, service_data: null, local_name: null, tx_power_level: null}, device: {platform_name: null, remote_id: 1D9E1233-9C4E-5CA5-F585-47726150405A}, rssi: -63}}
flutter: [FBP] [[ OnScanResponse ]] result: {result: {advertisement_data: {manufacturer_data: null, service_uuids: null, connectable: 1, service_data: null, local_name: null, tx_power_level: 7}, device: {platform_name: null, remote_id: F8796A96-7256-FC32-8EE5-D854593ADBAF}, rssi: -86}}
flutter: [FBP] [[ OnScanResponse ]] result: {result: {advertisement_data: {manufacturer_data: null, service_uuids: null, connectable: 1, service_data: null, local_name: null, tx_power_level: 7}, device: {platform_name: null, remote_id: F8796A96-7256-FC32-8EE5-D854593ADBAF}, rssi: -86}}
```

**Comment by wxxedu** [comment] 2023-11-07 15:54
Also it seems to me that after calling the `stopScan`, the `scanResults` is still being updated.

**Comment by chipweinberger** [comment] 2023-11-07 18:34
also, make sure you cancel the scanResults subscription!

so that you don't have multiple listeners

**Comment by wxxedu** [comment] 2023-11-07 18:39
Thanks so much! I now have some ideas as to how to work around this problem in my code. 

The part that's relatively confusing to me is that in the beginning when I call the `startScan`, it works fine. Then after a few minutes, once I tap on the function that calls the `startScan` again, it becomes very laggy. I have double checked that I have indeed cancelled the subscriptions, but I guess I'll need to clear up the logic a bit more to see what actually is going on as well as give the directions that you mentioned a try.

Thanks :)

**Comment by chipweinberger** [comment] 2023-11-07 22:22
in 1.26.5 I've added some more filters & a `continuousUpdates` toggle. You can use these to try and reduce how often your callback it called to increase perf.

* **[Add]** scanning: `withRemoteIds`, `withNames`, `withKeywords` filters
* **[Add]** scanning: `continuousUpdates` option replaces former `allowDuplicates` option

**Comment by chipweinberger** [comment] 2023-11-09 01:38
also in 1.27.2, I added a small perf improvement 

[[Perf] scanning: only add keys to internal advertisment hashmap when they exist ](https://github.com/boskokg/flutter_blue_plus/commit/9ce5cc451ac197039e59bf1a6af856a8bae61731)

**Comment by chipweinberger** [comment] 2023-11-09 04:29
in 1.27.3, I've also added a `continuousDivisor` option with you can use to divide the total number of advertisements processed to 1/2, 1/3, 1/4, etc, as needed. It is per-device, so you still get the 1st advertisement from each device.

**Comment by jiangchengze** [comment] 2023-11-10 01:35
I encountered the same situation. Occasionally the UI stuck when entering the scanning interface. It is easier to reproduce on low-configuration mobile phones.

**Comment by chipweinberger** [comment] 2023-11-10 01:49
afaict, FBP is doing the minimum amount of work posssible. If you find a solution, lmk.

**Comment by chipweinberger** [comment] 2023-11-11 00:49
@jiangchengze , are you setting any scan filters? you should set as many as you can.

**Comment by joyhope** [comment] 2023-11-15 09:41
Is there any explanation for why slow happen?

I also met app slow problem,  the complete app UI is unable to refresh,  but is not related to the scan,  we are still tracing where the problems come from.   (Our slow app happened after 3 days when BLE data was received, the UI screen is very hard to refresh.)

**Comment by joyhope** [comment] 2023-11-16 07:14
We are still testing whether the slow problem happen again.  I though it was fixed due to https://github.com/boskokg/flutter_blue_plus/commit/3328ac5ad9c6dd54baf8668532a46d8e6273c154.

The improper isScanning state may cause the app to make a quick response, and startScan and app level stop/start process may cause conflicting.

**Comment by joyhope** [comment] 2023-11-16 23:45
It is very strange, The App slow problem is happening again after running 3 days.  The difficulty is that there is no exceptional log appeared.  Our regression test shows: that the problem happened since 1.20.x version.  Our last stable version is 1.17.6 (I guess) It is still in testing. 

I read the changed log, but I did not find a related part.  Is there any suggestion?

**Comment by chipweinberger** [comment] 2023-11-17 00:12
no suggestions. I don't know the reason either!

**Comment by joyhope** [comment] 2023-11-17 01:52
1.17.6 seems slowly become slow now.  The problem may be between 1.17.1 to 1.17.6.

**Comment by joyhope** [comment] 2023-11-17 03:21
Our code uses characteristic.lastValueStream for notification.  There is different  implement between 1.15.5 ~ 1.17.1.

The FBP makes a right changings.  Our code should chanage to  characteristic.onValueReceived.

I make test again.

**Comment by chipweinberger** [comment] 2023-11-17 03:51
@joyhope , changing random things is not going to be helpful.

You should take a `profile`. https://medium.com/dartlang/dart-devtools-analyzing-application-performance-with-the-cpu-profiler-3e94a0ec06ae

**Comment by AxelBlaz3** [comment] 2023-11-17 15:01
In my case, it's happening when I start writing to the BLE device. Usually, the write time takes about 10-15 min for me. The first few minutes are blazing fast, then the thermal throttling starts. It's so slow now.

**Comment by joyhope** [comment] 2023-11-19 03:16
My slow problem may be solved(Still in testing). I found the problem.  The subscription is not canceled because of a new stream listen.   With the time on, there are more and more subscriptions in the system. 

The onValueReceived keeps using one stream, but lastValueStream will always use a new stream.  It is my code problem, not related to FBP. 

I hope my test will finally confirm the problem.

**Comment by joyhope** [comment] 2023-11-19 04:14
`      readFastCharacteristic?.cancel();
      readFastCharacteristic = characteristic.onValueReceived.listen(null) <<===new
      //readFastCharacteristic = characteristic.lastValueStream.listen(null); <<==old`

The cancel did not use await, I am not clear whether it caused the slow performance.

**Comment by chipweinberger** [comment] 2023-11-19 05:58
@joyhope every time you call "listen" it creates a new stream subscription and takes more resources to feed that subscription.

"creating more streams" does not matter. it's the subscriptions that matter.

yes you need to cancel subscriptions. the readme has examples.

**Comment by joyhope** [comment] 2023-11-19 09:16
As the code, the cancel is did called, but does not with await.

`      readFastCharacteristic?.cancel();
      readFastCharacteristic = characteristic.onValueReceived.listen(null);`

Using lastValueStream meets the slow problem, but using onValueRecived seems no problem until now.  But I could not explain why this happened.   With await xxx.cancel() is the correct way, but without the await, I could not explain why caused slow.

**Comment by joyhope** [comment] 2023-11-19 14:54
My test failed.  The app BLE notification becomes slower 

The latest no slower verison is 1.15. 5 (mayb 1.15.x) , 1.17.x and 1.28.x all meet the slow problem. I checked my code again and again, but nothing found except the cancel.

**Comment by joyhope** [comment] 2023-11-19 15:05
I said the notification seemed slow, but the data was not lost.  The UI will be updated if the notification happens, but if the slow happens, the UI refresh becomes very slow. In the normal, the UI will be updated at least 10HZ. With time on, the UI update will become 1s and will be even more long.  I could explain why this happened.

**Comment by chipweinberger** [comment] 2023-11-19 20:15
@joyhope do you know how to profile code and determine why it is slow?

**Comment by joyhope** [comment] 2023-11-20 00:19
I know use profile mode. but if the profile is not stable in my test environment. Anyway, I will construct the mode.  The first goal is to make the current app become stable as quickly as possible. 

If 1.15.x is confirmed stable, I will profile with the latest FBP and give feedback.

**Comment by joyhope** [comment] 2023-11-20 02:24
1.15.5 is confirmed no slow problem.    This time the app is back to 1.15.10 version, and tests again.

**Comment by joyhope** [comment] 2023-11-21 02:43
Help confirm the code: 
`Future<T> fbpEnsureDeviceIsConnected(BluetoothDevice device, String function) {
    // Create a completer to represent the result of this extended Future.
    var completer = Completer<T>();

    // disconnection listener.
    var subscription = device.connectionState.listen((event) {
      if (event == BluetoothConnectionState.disconnected) {
        if (!completer.isCompleted) {
          completer.completeError(FlutterBluePlusException(
              ErrorPlatform.fbp, function, FbpErrorCode.deviceIsDisconnected.index, "Device is disconnected"));
        }
      }
    });

    // When the original future completes
    // complete our completer and cancel the subscription.
    this.then((value) {
      if (!completer.isCompleted) {
        subscription.cancel();
        completer.complete(value);
      }
    }).catchError((error) {
      if (!completer.isCompleted) {
        subscription.cancel();
        completer.completeError(error);
      }
    });

    return completer.future;
  }`

The first completer.completeError(FlutterBluePlusException) does not call subscription.cancel() , whether this will cause the problem?

**Comment by joyhope** [comment] 2023-11-22 02:26
1.15.10 library has been testing for two days,  up till now it is working perfectly.  It is very strange that we just changed the FBP version, and the problem seems gone.  

I compared 1.15.x with 1.17.1 again and again,  I could not find any clue related such slow problem.  After the 1.15.10 passes 3 days test,  I will debug the latest FBP library.

**Comment by joyhope** [comment] 2023-11-23 00:25
The app confirmed the 1.15.10 version worked without fault.  I test a little longer and then try to debug the problem.

**Comment by joyhope** [comment] 2023-11-29 12:42
Just found many changes happened.  I will use the latest version to make a profile build.

**Comment by joyhope** [comment] 2023-11-30 12:49
I'd rather find the problem by the code review. 

I suspect the code is different between 1.15.X and 1.17.1

`  Stream<T> get stream {
    return latestValue != null
      ? _controller.stream.newStreamWithInitialValue(latestValue!)
      : _controller.stream;
  }`

In the code, the _StreamController object gets a stream, which always causes a new Stream. The new Stream may not be GC by the engine. 

I have not made a test on the code.

**Comment by chipweinberger** [comment] 2023-11-30 17:16
that's an interesting thought

**Comment by joyhope** [comment] 2023-12-02 02:05
I changed the code and made a test. It needs 3 days to get the result. (It is in the normal usage state.). I will update the result. Hope it works.

**Comment by joyhope** [comment] 2023-12-04 00:25
I confirmed using 1.15.10 was a good version. It has been working over 10 days.

**Comment by joyhope** [comment] 2023-12-04 10:49
1. what happen when it slows?
App real-time draw data from Bluetooth. The data is correctly received, but the app draws data causing a frame drop.  It drawed data frame becomes much longer than the beginning time.  In the beginning, 10hz refresh is no problem, but slow will cause 1s, 2s, even10s refresh.

2. is the app open for 10 days?
The app works for the device.  If start it will be ready for display data.  It could be running for months, without restart. 

3. does it ever recover?
It never recovered. it becomes worse and worse until the app touch screen is unable to work.

**Comment by chipweinberger** [comment] 2023-12-04 18:44
@joyhope I would add logs all over your program with timestamps so you can determine which part of the application is getting slow 

it might not be a FBP issue

my guess is that some data is growing and growing.

**Comment by joyhope** [comment] 2023-12-05 01:44
Maybe,  but it is true that  I backed to 1.15.10,  and then the problem is gone.  The library has been used for a very long time.  I first use flutter_blue, and then, you take over and go on.

The problem suddenly happened in the Oct, so I checked my app first.  The last step is thought the FBP caused.

**Comment by joyhope** [comment] 2023-12-05 15:32
I use 1.16.6 for the smaller problem versions.  I hope to get the exact problem version and then make analysis.

**Comment by joyhope** [comment] 2023-12-06 00:31
The version from 1.16.6 ~1.16.10 does not work for onValueReceived.  The App is unable to test. 1.16.12 said fixed the problem (regression 1.16.3)    This may be a clue for what happened.  The slow is mainly about onValueReceived.

**Comment by joyhope** [comment] 2023-12-09 00:30
The newer adapterState is create new stream, the old lib(1.16.12) return the same stream.  My app is using StreamBuild in the stateless widget. 

The FBP demo is using state widget, and using listen the state. 

Whether the StreamBuild use case with the new implement cause the problem?  Just a guess. Because I checked the code again and again,  nothing was found.

**Comment by joyhope** [comment] 2023-12-09 09:02
I used 1.17.1 version with adapteState 1.16.12 implement, so the adapterState is always the same stream object, otherwise, the new adapterState will not be closed.  

I made the test again. I hope it will be confirmed.

**Comment by joyhope** [comment] 2023-12-09 09:33
I am still not confident about the "problem".   Good is the problem is start begin 1.17.0, or 1.17.1.  Currently, I am just closer.

**Comment by joyhope** [comment] 2023-12-09 11:05
The problem does not happen in my case.  I made a test on 1.17.0， go on finding the first problem version.

**Comment by joyhope** [comment] 2023-12-09 11:21
I still have questions about this code

`  static Stream<BluetoothAdapterState> get adapterState async* {
    // start listening now so we do not miss any changes
    var buffer = _BufferStream.listen(FlutterBluePlus._methodStream.stream
        .where((m) => m.method == "OnAdapterStateChanged")
        .map((m) => m.arguments)
        .map((args) => BmBluetoothAdapterState.fromMap(args))
        .map((s) => _bmToBluetoothAdapterState(s.adapterState)));

    // initial state
    BluetoothAdapterState initialValue = await _invokeMethod('getAdapterState')
        .then((args) => BmBluetoothAdapterState.fromMap(args))
        .then((s) => _bmToBluetoothAdapterState(s.adapterState));

    // make sure the initial value has not become out of date
    // while we were awaiting for the initial state
    if (buffer.hasReceivedValue == false) {
      yield initialValue;
    }

    // stream
    yield* buffer.stream;
  }`

buffer is always get new object, so the buffer.hasReceivedValue == false is true, and then he buffer is nerver close?

**Comment by chipweinberger** [comment] 2023-12-09 13:47
it should close when you cancel the stream subscription i think

good luck

**Comment by joyhope** [comment] 2023-12-09 14:23
The code 
`
if (buffer.hasReceivedValue == false) {
  yield initialValue;
}
`

In 1.17.1 , I found is alway == false.  It means the buffer stream is always new, and never closed.  The stream is unable to be closed in the app.

**Comment by chipweinberger** [comment] 2023-12-09 21:48
hmm yes maybe BufferStream is not being closed.

I think buffer stream is not necessary

we can something like this 

if (_adapterStateNow != initialValue) {
return xxx. newStreamWithInitialValue(_adapterStateNow)
}

**Comment by chipweinberger** [comment] 2023-12-09 22:06
try master branch! thanks for finding this issue! you did a lot of work!

**Comment by joyhope** [comment] 2023-12-10 09:42
I will still take time to understand the problem, and I will test the latest code, and give feedback.  

Thank you for continuously improving the project.

**Comment by joyhope** [comment] 2023-12-13 00:07
I tried the master branch version, and after running 2 days, the app displayed slowly again.  It is a tough problem. I had to back 1.17.0, and check whether this is the latest no-problem version. And try to find the problem between "good" and "bad". 

Otherwise, I had to use profile mode. In fact, I am afraid that even with the profile version, the problem is still had to detect.

**Comment by chipweinberger** [comment] 2023-12-13 07:31
that's very surprising.

perhaps you can commenting out parts of your code to try and limit the causes. 

also, you should try and make the problem happen faster.

**Comment by chipweinberger** [comment] 2023-12-15 04:50
I've release 1.30.5 with the previous changes. It's still an improvement even though it does not fix the problem for you.

**Comment by ycnc1314** [comment] 2023-12-15 09:39
`class _NewStreamWithInitialValueTransformer<T> extends StreamTransformerBase<T, T> {
  final T initialValue;

  _NewStreamWithInitialValueTransformer(this.initialValue);

  @override
  Stream<T> bind(Stream<T> stream) {
/*    if (stream.isBroadcast) {
      return _bind(stream).asBroadcastStream();
    } else {
      return _bind(stream);
    }*/
    return _bind(stream);
  }
...
}`

**Comment by joyhope** [comment] 2023-12-16 02:40
I read this part many many times.  Why this is the problem?

**Comment by joyhope** [comment] 2023-12-16 02:45
I see this: [[Improve] mergeStreams: cancel all subscriptions & close on done](https://github.com/boskokg/flutter_blue_plus/commit/fa7d15f32ee611cfefc4d1770287210f0cd5a91a).   This is also a potential problem.  Thanks for this. 

I will finish the 1.17.0 test on Sunday, and then use the latest version.   As my test, 1.17.0 is the last version that could work for a long time.  

The problem should be between 1.17.0 and 1.17.1.   I read different more than 5 times.  It is a puzzle.

**Comment by joyhope** [comment] 2023-12-18 00:33
Confirmed 1.17.0 is last stable for long time version.  I use 1.30.5 for test.

**Comment by ycnc1314** [comment] 2023-12-18 02:00
> I read this part many many times. Why this is the problem?

‘’’
utils.dart
class _NewStreamWithInitialValueTransformer<T> extends StreamTransformerBase<T, T> {
  final T initialValue;

  _NewStreamWithInitialValueTransformer(this.initialValue);

  @override
  Stream<T> bind(Stream<T> stream) {
    //------------------------------------change here
/*    if (stream.isBroadcast) {
      return _bind(stream).asBroadcastStream();
    } else {
      return _bind(stream);
    }*/
    return _bind(stream);
    //----------------------------------------------
  }

  Stream<T> _bind(Stream<T> stream) {
    StreamController<T>? controller;
    StreamSubscription<T>? subscription;

    controller = StreamController<T>(
      onListen: () {
        // Emit the initial value
        controller?.add(initialValue);

        subscription = stream.listen(
          controller?.add,
          onError: (Object error) {
            controller?.addError(error);
            controller?.close();
          },
          onDone: controller?.close,
        );
      },
      onPause: ([Future<dynamic>? resumeSignal]) {
        subscription?.pause(resumeSignal);
      },
      onResume: () {
        subscription?.resume();
      },
      onCancel: () {
        return subscription?.cancel(); 
        //------------------'asBroadcastStream' has different controller,can't cancel this subscription
        //You can use  stream.asBroadcastStream(onListen,onCancel)
        //But it's not necessary
      },
      sync: true,
    );

    return controller.stream;
  }
}
‘’’

**Comment by chipweinberger** [comment] 2023-12-18 03:17
> You can use  stream.asBroadcastStream(onListen,onCancel)

why do you think it is not necessary?

We want to return a broadcast stream, if the original stream was broadcast. This would otherwise be a breaking change.

**Comment by ycnc1314** [comment] 2023-12-18 03:42
> why do you think it is not necessary?
> 
> We want to return a broadcast stream, if the original stream was broadcast. This would otherwise be a breaking change.

```

extension _StreamNewStreamWithInitialValue<T> on Stream<T> {
  Stream<T> newStreamWithInitialValue(T initialValue) {
    return transform(_NewStreamWithInitialValueTransformer(initialValue));
  }
}

  static Stream<BluetoothAdapterState> get adapterState async* {
    ...
    yield* FlutterBluePlus._methodStream.stream
        .where((m) => m.method == "OnAdapterStateChanged")
        .map((m) => m.arguments)
        .map((args) => BmBluetoothAdapterState.fromMap(args))
        .map((s) => _bmToAdapterState(s.adapterState))
        .newStreamWithInitialValue(_bmToAdapterState(_adapterStateNow!));
    }
```
Each subscription is a new stream.Each new stream is a copy of the original stream.

**Comment by chipweinberger** [comment] 2023-12-18 04:58
Correct. If users open a lot of streams it will cause perf problems because each one is a new copy. This is part of the API we should not change.

As long as users so not open too many streams, and close the old ones, it should not be a perf problem.

**Comment by ycnc1314** [comment] 2023-12-18 06:25
> 正确。返回流的唯一方法_有了初始值_就是创建一个新的流。如果用户打开大量的流，会导致性能问题，因为每个流都是一个新的控制器。这是我们不应该改变的API的一部分。
> 
> 只要用户不打开太多的流，并关闭旧的流，应该不是性能问题。


```
BluetoothCharacteristic.dart

  Future<void> write(List<int> value,
      {bool withoutResponse = false, bool allowLongWrite = false, int timeout = 15}) async {
     ... ...
      // invoke
      await FlutterBluePlus._invokeMethod('writeCharacteristic', request.toMap());

      // wait for response so that we can:
      //  1. check for success (writeWithResponse)
      //  2. wait until the packet has been sent, to prevent iOS & Android dropping packets (writeWithoutResponse)
      int t = DateTime.now().millisecondsSinceEpoch;
      BmCharacteristicData response = await futureResponse
          .fbpEnsureAdapterIsOn("writeCharacteristic")/////-----------here
          .fbpEnsureDeviceIsConnected(device, "writeCharacteristic")////----------------here
          .fbpTimeout(timeout, "writeCharacteristic");
      print('futureResponse:${DateTime.now().millisecondsSinceEpoch-t}');
      // failed?
      if (!response.success) {
        throw FlutterBluePlusException(_nativeError, "writeCharacteristic", response.errorCode, response.errorString);
      }

      return Future.value();
    } finally {
      mtx.give();
    }
  }
---------------------------------------------------------------------------------------
utils.dart

  Future<T> fbpEnsureAdapterIsOn(String function) {
    // Create a completer to represent the result of this extended Future.
    var completer = Completer<T>();

    // disconnection listener.
    var subscription = FlutterBluePlus.adapterState.listen((event) {/////--------------------here,  Can't cancel subscription from function _bind().
      if (event == BluetoothAdapterState.off || event == BluetoothAdapterState.turningOff) {
        if (!completer.isCompleted) {
          completer.completeError(FlutterBluePlusException(
              ErrorPlatform.fbp, function, FbpErrorCode.adapterIsOff.index, "Bluetooth adapter is off"));
        }
      }
    });
   ... ...
    return completer.future;
  }
}

  Future<T> fbpEnsureDeviceIsConnected(BluetoothDevice device, String function) {
    // Create a completer to represent the result of this extended Future.
    var completer = Completer<T>();

    // disconnection listener.
    var subscription = device.connectionState.listen((event) {//---------------------here
      if (event == BluetoothConnectionState.disconnected) {
        if (!completer.isCompleted) {
          completer.completeError(FlutterBluePlusException(
              ErrorPlatform.fbp, function, FbpErrorCode.deviceIsDisconnected.index, "Device is disconnected"));
        }
      }
    });
   ... ...
    return completer.future;
  }

```

**Comment by ycnc1314** [comment] 2023-12-18 06:26
> Correct. The only way to return a stream _with an initial value_ is to create a new stream. If users open a lot of streams it will cause perf problems because each one is a new controller. This is part of the API we should not change.
> 
> As long as users do not open too many streams, and close the old ones, it should not be a perf problem.


```
BluetoothCharacteristic.dart

  Future<void> write(List<int> value,
      {bool withoutResponse = false, bool allowLongWrite = false, int timeout = 15}) async {
     ... ...
      // invoke
      await FlutterBluePlus._invokeMethod('writeCharacteristic', request.toMap());

      // wait for response so that we can:
      //  1. check for success (writeWithResponse)
      //  2. wait until the packet has been sent, to prevent iOS & Android dropping packets (writeWithoutResponse)
      int t = DateTime.now().millisecondsSinceEpoch;
      BmCharacteristicData response = await futureResponse
          .fbpEnsureAdapterIsOn("writeCharacteristic")/////-----------here
          .fbpEnsureDeviceIsConnected(device, "writeCharacteristic")////----------------here
          .fbpTimeout(timeout, "writeCharacteristic");
      print('futureResponse:${DateTime.now().millisecondsSinceEpoch-t}');
      // failed?
      if (!response.success) {
        throw FlutterBluePlusException(_nativeError, "writeCharacteristic", response.errorCode, response.errorString);
      }

      return Future.value();
    } finally {
      mtx.give();
    }
  }
---------------------------------------------------------------------------------------
utils.dart

  Future<T> fbpEnsureAdapterIsOn(String function) {
    // Create a completer to represent the result of this extended Future.
    var completer = Completer<T>();

    // disconnection listener.
    var subscription = FlutterBluePlus.adapterState.listen((event) {/////--------------------here,  Can't cancel subscription from function _bind().
      if (event == BluetoothAdapterState.off || event == BluetoothAdapterState.turningOff) {
        if (!completer.isCompleted) {
          completer.completeError(FlutterBluePlusException(
              ErrorPlatform.fbp, function, FbpErrorCode.adapterIsOff.index, "Bluetooth adapter is off"));
        }
      }
    });
   ... ...
    return completer.future;
  }
}

  Future<T> fbpEnsureDeviceIsConnected(BluetoothDevice device, String function) {
    // Create a completer to represent the result of this extended Future.
    var completer = Completer<T>();

    // disconnection listener.
    var subscription = device.connectionState.listen((event) {//---------------------here
      if (event == BluetoothConnectionState.disconnected) {
        if (!completer.isCompleted) {
          completer.completeError(FlutterBluePlusException(
              ErrorPlatform.fbp, function, FbpErrorCode.deviceIsDisconnected.index, "Device is disconnected"));
        }
      }
    });
   ... ...
    return completer.future;
  }

```

**Comment by joyhope** [comment] 2023-12-18 06:44
All list codes are important, I read them many times, but could not confirm my suspicions.  

Through the code change, I think the explanation is corrected.  Good point.  

It is good to accept the _NewStreamWithInitialValueTransformer change. It may be easy to process, no feature is lost.

**Comment by ycnc1314** [comment] 2023-12-18 07:01
> All list codes are important, I read them many times, but could not confirm my suspicions.
> 
> Through the code change, I think the explanation is corrected. Good point.
> 
> It is good to accept the _NewStreamWithInitialValueTransformer change. It may be easy to process, no feature is lost.

Here's how I solved the problem of slow ui, you can test it out

**Comment by joyhope** [comment] 2023-12-18 07:08
It is good to hear that you solved this problem already.  It blocked me for 2 months. I had to use an old "good" library. I think it is good to "correct" it, so all the users of this library will benefit. 

Wait author improve.   Many thanks.

**Comment by chipweinberger** [comment] 2023-12-18 07:15
I think this solution could work. It does not use `asBroadcastStream`

```
// Helper for 'newStreamWithInitialValue' method for streams.
class _NewStreamWithInitialValueTransformer<T> extends StreamTransformerBase<T, T> {
  final T initialValue;
  StreamController<T>? controller;
  StreamSubscription<T>? subscription;

  _NewStreamWithInitialValueTransformer(this.initialValue);

  @override
  Stream<T> bind(Stream<T> stream) {
    if (stream.isBroadcast) {
      return _bind(stream, broadcast: true);
    } else {
      return _bind(stream);
    }
  }

  Stream<T> _bind(Stream<T> stream, {bool broadcast = false}) {
    void onListen() {
      // Emit the initial value
      controller?.add(initialValue);

      subscription = stream.listen(
        controller?.add,
        onError: (Object error) {
          controller?.addError(error);
          controller?.close();
        },
        onDone: controller?.close,
      );
    }

    void onPause() {
      subscription?.pause();
    }
    
    void onResume() {
      subscription?.resume();
    }

    FutureOr<void> onCancel() {
      return subscription?.cancel();
    }

    if (broadcast) {
      controller = StreamController<T>.broadcast(
        onListen: onListen,
        onCancel: onCancel,
        sync: true,
      );
    } else {
      controller = StreamController<T>(
        onListen: onListen,
        onPause: onPause,
        onResume: onResume,
        onCancel: onCancel,
        sync: true,
      );
    }

    return controller!.stream;
  }
}
```

**Comment by joyhope** [comment] 2023-12-18 07:19
Good to see this change.   Thank you.

**Comment by chipweinberger** [comment] 2023-12-18 07:21
let me know if m suggestion works for you

**Comment by joyhope** [comment] 2023-12-18 07:23
I will test today.  And make feedback.

**Comment by chipweinberger** [comment] 2023-12-18 07:31
I've pushed change to master branch!

**Comment by joyhope** [comment] 2023-12-21 10:16
i confirmed the bug is fixed.  The app does not become slow since this change.  Thank you. I could use the latest version now.

**Comment by chipweinberger** [comment] 2023-12-21 15:57
wow that is amazing!

**Closed** 2023-12-21 15:58 UTC
Labels: help
