### ISSUE TITLE
[Bug]: Android: multiple msd with same manufacturer_id doesn't work

### ISSUE THREAD

**Issue by zwells** [boskokg/flutter_blue_plus#785] opened 2024-02-05 19:47 UTC
### Requirements

- [X] I've looked at the README 'Common Problems' section

### Have you checked this problem on the example app?

Yes

### FlutterBluePlus Version

1.31.13

### Flutter Version

3.16.9

### What OS?

Android

### OS Version

Android 7/8/9/10/11/12

### Bluetooth Module

Nordic nRF52811

### What is your problem?

Failing to get one portion of our manufacturer data (the shorter of the two) in FlutterBluePlus ScanResult

FlutterBluePlus returns: `I/flutter (20425): {rssi: -81, connectable: 1, manufacturer_data: {321: 080c5cc6e81464c101070111c452000000}, remote_id: C1:64:14:E8:C6:5C, service_data: {}, service_uuids: [180a]}`

nRF Connect shows 2nd portion of manufacturer data:
![MicrosoftTeams-image (3)](https://github.com/boskokg/flutter_blue_plus/assets/13053993/3efeca30-4b7e-4f13-95c4-13bc48ccd6ee)
![MicrosoftTeams-image (2)](https://github.com/boskokg/flutter_blue_plus/assets/13053993/88dfffcd-c007-403c-b30c-6aeeede98095)

### Logs

```shell
I/flutter (20425): {rssi: -81, connectable: 1, manufacturer_data: {321: 080c5cc6e81464c101070111c452000000}, remote_id: C1:64:14:E8:C6:5C, service_data: {}, service_uuids: [180a]}
```

**Comment by zwells** [comment] 2024-02-05 22:09
Some odd behavior to note: The 2nd half _IS_ coming through on a Samsung Galaxy running Android 13. Not coming through on all others.

Continuing to troubleshoot.

**Comment by martyn-schnap** [comment] 2024-02-06 11:24
Thank you for looking into this, I came to report the same issue. Mine works correctly on iOS but not on Android 

e.g.:
Android (pixel 4a):
0000000000000000000000000007d600001403060b72a800

iOS:
e2eba5341c47000000000000000000000000010000000000000000000000000007d600001503060b72a800

I will also try and troubleshoot further.

**Full Scan Responses:**

Android (pixel 4a):
I/flutter ( 7645): [FBP] [[ OnScanResponse ]] result: {advertisements: [{rssi: -69, connectable: 1, manufacturer_data: {119: 0000000000000000000000000007d600001403060b72a800}, remote_id: E2:EB:A5:34:1C:47, platform_name: ENS, tx_power_level: 4, service_data: {}, adv_name: ENS}]}

iOS:
flutter: [FBP] [[ OnScanResponse ]] result: {advertisements: [{manufacturer_data: {119: e2eba5341c47000000000000000000000000010000000000000000000000000007d600001503060b72a800}, rssi: -61, remote_id: 66EED426-7F43-22D6-154D-D4C6B0DCB573, platform_name: ENS, tx_power_level: 4, connectable: 1, adv_name: ENS}]}

**Comment by zwells** [comment] 2024-02-06 17:01
It can be seen in the raw data of `result.GetScanRecord().GetBytes();` for Android, but the plugin doesn't give access to it, and pull requests for this have been denied in the past.

Android with **GetBytes**
I/flutter (21478): [FBP] [[ OnScanResponse ]] result: {advertisements: [{rssi: -62, connectable: 1, manufacturer_data: {321: 080c5cc6e81464c101070111c452000000}, remote_id: C1:64:14:E8:C6:5C, service_data: {}, service_uuids: [180a], raw_data: 02010603020a180bff4101070a411150c4800014ff4101080c5cc6e81464c101070111c452000000}]}

**Comment by chipweinberger** [comment] 2024-02-06 23:05
so the reason for this bug is pretty simple.

you have two MSD fields, and they both have the same `manufacturerId`

FBP was designed to only allow one MSD per `manufacturerId`.

We need to change the dart api to fix this. We'll need to return a List<MsdData> instead of a Map<int, List<int>.

**Comment by chipweinberger** [comment] 2024-02-06 23:16
We should use this

```
class BmScanAdvertisement {
  final List<List<int>> manufacturerData;
```

**Comment by chipweinberger** [comment] 2024-02-06 23:18
you can also delete this iOS code, since we wont use map keys anymore

```
        // first 2 bytes are manufacturerId (little endian)
        uint8_t bytes[2];
        [manufData getBytes:bytes length:2];
        unsigned short manufId = (unsigned short) (bytes[0] | bytes[1] << 8);

        // trim off first 2 bytes
        NSData* trimmed = [manufData subdataWithRange:NSMakeRange(2, manufData.length - 2)];
        NSString* hex = [self convertDataToHex:trimmed];
```

**Comment by martyn-schnap** [comment] 2024-02-09 13:50
Would it not be easier to append the additional MSD field instead of overwriting, so that we have one longer list per manufacturerId?
This would keep everything is the same structure as we have now?

I feel like this already happens in iOS (although cannot confirm) as I currently get one long list containing both on that platform.

**Comment by chipweinberger** [comment] 2024-02-09 16:45
the issue says "Android 10 / iOS 17.3"

but if you can confirm that ios behaves that way then okay, you're right 

then we'd just need to make android behave the same way

**Comment by zwells** [comment] 2024-02-09 16:50
I can confirm I'm getting the appended `manufacturerData` as-is on iOS. I agree making android behave the same way would resolve the issue.

**Comment by chipweinberger** [comment] 2024-02-09 16:54
okay great. please open a PR to fix android :)

**Comment by zwells** [comment] 2024-02-09 21:19
Looks like the problem actually lies in Android's `adv.getManufacturerSpecificData()` call not returning it...

**Comment by chipweinberger** [comment] 2024-02-09 21:45
If that is the case you need to get the raw  bytes and parse it yourself. 

you can look here for inspiration: https://github.com/boskokg/flutter_blue_plus/pull/772

**Comment by chipweinberger** [comment] 2024-02-14 22:41
@zwells , @martyn-schnap , if you need this fixed please fix it and open a PR.

**Comment by chipweinberger** [comment] 2024-02-26 23:04
@zwells @martyn-schnap , bump. Do you not need this anymore?

**Comment by zwells** [comment] 2024-02-26 23:17
I fixed it locally for our use-case by reading the raw bytes at the app level, I'm not sure how it needs to be parsed in order to be appropriate for other manufacturers.

**Comment by MrCsabaToth** [comment] 2024-03-13 01:19
> I fixed it locally for our use-case by reading the raw bytes at the app level, I'm not sure how it needs to be parsed in order to be appropriate for other manufacturers.

* The appearance handling required processing of the raw bytes since there's no native `adv.getAppearance()` like call.
* Your case is similar to appearance (`dataType == 0x19`) except that you have `dataType == 0xFF`.
* Note that since the byte is signed, you'd possibly need to perform an extra `& 0xFF` to safely test for "large" byte values: `int dataType = bytes[n + 1] & 0xFF;`
* In the quoted code snippet when the appearance is spotted the loop shortcuts immediately. Manufacturer loop would keep on going and peek into all data chunks and would keep a byte array to append to.
* Note, that there were consideration and time put into harden the malformed data scenarios, those need to be kept. I'm almost thinking if the appearance and the manufacturer data should use the same loop. That would make the loop cyclomatically more complex, but the array would be parsed only one time. The question is how much that parse performance matters during scan, usually these are no more than 40 byte strings.
* I wonder if the Bluetooth Low Energy (or non low energy as well?) specifications allows multiple chunks with the same data type. If yes, then this could be actually an API bug in the Bluetooth layer of Android. I filed an issue: https://issuetracker.google.com/issues/329198133

**Comment by MrCsabaToth** [comment] 2024-03-13 01:27
Bonus question: what kind of device is this? Manufacturer ID 321 (0x141) is FedEx (according to BT / GATT standards), wow!

**Comment by zwells** [comment] 2024-03-13 02:18
https://www.youtube.com/watch?app=desktop&v=LRyk_fDBbZA

**Comment by MrCsabaToth** [comment] 2024-03-13 02:27
> https://www.youtube.com/watch?app=desktop&v=LRyk_fDBbZA

Interesting, so this is essentially a Bluetooth tracker such as [Tile](https://www.tile.com/en-us), [Nut](https://www.nutfind.com/), or - lately - Apple AirTag? An interesting thing I learned is that Bluetooth LE's first mainstream use was these type of trackers, and that's why for a very long time Android Bluetooth required location permissions (even if your BLE didn't have to do anything with location). This requirement only got lifted with the last few recent Android generations.

**Comment by MrCsabaToth** [comment] 2024-03-15 18:53
@zwells Not sure if it was you who commented on https://issuetracker.google.com/issues/329198133, but could you please paste any kind of LogCat or even Flutter / FBP logs? They need to put us through the ringer with some standard stuff, so they need something so they can check that checkbox. I think it'd be great if this was also solved at the core level by that issue.

**Comment by MrCsabaToth** [comment] 2024-03-15 18:57
@zwells Also whoever commented posted a URL to some token maker website but it doesn't seem to do anything with Bluetooth, it's some site for "making rpg character token" for games. URL needs to be corrected.

**Comment by zwells** [comment] 2024-03-15 19:07
Wasn't me, I'll try to get the bug report to them next week

**Comment by chipweinberger** [comment] 2024-04-06 19:42
@MrCsabaToth , can you tackle this bug? would be great to have your help!

**Comment by chipweinberger** [comment] 2024-04-06 19:53
```
Map<Integer, List<Integer>> getManufacturerSpecificData(List<Integer> bytes) {
    Map<Integer, List<Integer>> msd = new HashMap<>();
    int n = 0;
    while (n < bytes.size()) {
        int fieldLen = bytes.get(n) & 0xFF;
        
        // no more or malformed data
        if (fieldLen <= 0) {
            break;
        }

        // Ensuring we don't go past the bytes array
        if (n + fieldLen >= bytes.size()) {
            break;
        }

        int dataType = bytes.get(n + 1);

        // Manufacturer Specific Data type check
        // At least 4 bytes: 2 for manufacturer ID, 1 for dataType, 1+ for data
        if (dataType == 0xFF && fieldLen > 3) { 

            int manufacturerId = (bytes.get(n + 3) & 0xFF) << 8 | (bytes.get(n + 2) & 0xFF);

            List<Integer> data = new ArrayList<>();

            // Starting from n+4 because manufacturerId occupies n+2 and n+3
            for (int i = n + 4; i < n + fieldLen + 1; i++) {
                data.add(bytes.get(i));
            }

            // add to map
            if (manufacturerData.containsKey(manufacturerId)) {
                // If the manufacturer ID already exists, append the new data to the existing list
                msd.get(manufacturerId).addAll(data);
            } else {
                // Otherwise, put the new manufacturer ID and its data into the map
                msd.put(manufacturerId, data);
            }
        }

        n += fieldLen + 1;
    }

    return msd;
}

```

**Comment by MrCsabaToth** [comment] 2024-04-07 07:04
I'm traveling to Google Cloud Next and will be busy next week.
I can confirm possibly that some code wouldn't cause any regression regarding the appearance data or some Bluetooth functionality.
@zwells do you have multiple of these FedEx tags you could mail to Chip? Maybe also me?

**Comment by chipweinberger** [comment] 2024-04-07 07:36
@MrCsabaToth its multiple msd *within the same advertisement*. not from multiple different devices.

**Comment by MrCsabaToth** [comment] 2024-04-07 19:24
> @MrCsabaToth its multiple msd with same id *within the same advertisement*. not from multiple different devices.

@zwells has that FedEx SenseAware ID tag which has this.

**Comment by zwells** [comment] 2024-04-08 16:16
Yes, I can mail them out if needed. Feel free to email your shipping address to zachary-wells@outlook.com

**Comment by chipweinberger** [comment] 2024-04-22 06:28
@MrCsabaToth updates?

**Comment by MrCsabaToth** [comment] 2024-04-22 18:14
I haven't got the tag in the mail yet.

**Comment by MrCsabaToth** [comment] 2024-04-30 18:04
I got the two tags in the mail, but I'll only have time to debug on Sunday (hopefully), this week is quite busy.

**Comment by MrCsabaToth** [comment] 2024-05-06 06:53
I had to massage the proposed `getManufacturerSpecificData`, staying with `byte[]`, because `getBytes` supplies that and the hex conversion in the end needs that as well, so `List<Integer>` was unnecessary.

With that the data from the two FedEx tags I got with the example app's Scan:
![Screenshot_20240505-233907](https://github.com/boskokg/flutter_blue_plus/assets/744949/9cfc257d-cf04-4be1-8e4b-8896ad0b0b22)
![Screenshot_20240505-233923](https://github.com/boskokg/flutter_blue_plus/assets/744949/c41d5b32-ee54-4f93-8d55-2289464962eb)

As a reference the data displayed structured by nRF Connect (shown by @zwells as well earlier):
![Screenshot_20240505-155757](https://github.com/boskokg/flutter_blue_plus/assets/744949/0236e2f7-4452-414e-adae-ba77b2232067)
![Screenshot_20240505-155835](https://github.com/boskokg/flutter_blue_plus/assets/744949/0a6e6d55-0ec6-4620-b7a7-1c3f30f90a81)

**Comment by chipweinberger** [comment] 2024-05-06 07:58
awesome

**Comment by chipweinberger** [comment] 2024-05-06 07:59
and this matches ios behaior?

**Comment by MrCsabaToth** [comment] 2024-05-06 16:31
I went along the lines of what @zwells told. I have an iPad but cannot debug. I'll do some additional testing.

**Comment by MrCsabaToth** [comment] 2024-05-06 20:58
Here are some tests with Android 9 (Moto g):
![IMG_20240506_100500131](https://github.com/boskokg/flutter_blue_plus/assets/744949/aea9db7b-e6a6-4de8-9f8b-6addf8301960)
![IMG_20240506_100409766](https://github.com/boskokg/flutter_blue_plus/assets/744949/97cb7d83-66b2-4171-af1c-6d9402757cf7)

And Android 6.0.1 x86 (Atom, ASUS ZenFone):
![IMG_20240506_101334886](https://github.com/boskokg/flutter_blue_plus/assets/744949/f648e8ef-eb13-43c2-9b14-d9a6310c7d3f)

Can someone test and verify on an iOS device that this matches? As a user I looked at nRF Connect on iOS. It's quite interesting: I see that it doesn't get the appearance data. I also see that it shows the first occurrence (the shorter one) of the MSD for the FedEx tags. However FBP might differ from that and can show the merged one what @zwells describes?

**Comment by chipweinberger** [comment] 2024-05-06 21:45
can you run FBP on your ipad?

**Comment by chipweinberger** [comment] 2024-05-06 21:58
if it shows the shorter one only, then that means the behavior that @zwells described is wrong and we should revert the commit

**Comment by zwells** [comment] 2024-05-06 22:02
I will build the example and double check, but I'm pretty sure I get the full msd on iOS as-is

**Comment by chipweinberger** [comment] 2024-05-06 22:11
thanks @zwells !

**Comment by zwells** [comment] 2024-05-06 22:23
Confirming same behavior as nRF connect (iPhone 13) ![image](https://github.com/boskokg/flutter_blue_plus/assets/13053993/fde0d399-ece3-42f7-890b-bf37096a197a) ![image](https://github.com/boskokg/flutter_blue_plus/assets/13053993/5a7553a8-2460-48fd-a039-a91f0144a242)

**Comment by chipweinberger** [comment] 2024-05-06 23:06
thanks for the confirmation.

so, we can close this issue? since there is no way to solve this on iOS

for android, we can expose the raw advertisement data

an imperfect solution

**Comment by MrCsabaToth** [comment] 2024-05-06 23:08
Wait @chipweinberger, looks like @zwells's iOS device confirms what he says, data is merged in FBP example app (his latest top screenshot) and the nRF Connect (bottom screenshot), both show merged data.

**Comment by zwells** [comment] 2024-05-06 23:11
@MrCsabaToth Correct. Sorry for the confusion. I meant that iOS merges correctly.

**Comment by MrCsabaToth** [comment] 2024-05-06 23:16
Great, so the PR works!

**Comment by chipweinberger** [comment] 2024-05-07 03:31
great. I'll push a new version tomorrow then.

**Comment by chipweinberger** [comment] 2024-05-07 04:45
fixed in 1.32.5

**Closed by chipweinberger** 2024-05-07 04:45 UTC
Labels: bug

**Comment by MrCsabaToth** [comment] 2024-09-21 02:37
There was an off-by-one error and @chipweinberger fixed it here https://github.com/chipweinberger/flutter_blue_plus/commit/2e795ba92ce3c3bcb3f95563c8b217993033460c and released with [1.32.7](https://github.com/chipweinberger/flutter_blue_plus/commit/6f5cf7c08ab591e7e9a45deeca74db023b3b9e60)

**Comment by MrCsabaToth** [comment] 2024-09-21 02:40
Interesting news: the [native Android issue](https://issuetracker.google.com/issues/329198133) related to this marked as fixed and probably will be released with the next Android version. We should keep an eye out how it'll affect Flutter Blue Plus.

**Comment by chipweinberger** [comment] 2024-09-21 09:24
we wont be affected. we use `adv.getBytes();`

in otherwords, we rewrote the function because of that bug.

```
    Map<Integer, byte[]> getManufacturerSpecificData(ScanRecord adv) {
        byte[] bytes = adv.getBytes();
        Map<Integer, byte[]> manufacturerDataMap = new HashMap<>();
        int n = 0;
        while (n < bytes.length) {
```
