### ISSUE TITLE
Cant find any devices while flutter blue scanning 

### ISSUE THREAD

**Issue by thebeastxdxd** [boskokg/flutter_blue_plus#233] opened 2023-04-06 10:27 UTC
This issue is a copy from flutter blue. looks like it happens in this package as well.
The answer for us was Giving GPS(location) permissions to our app.
We only needed to do this when we built and deployed from a mac machine.
link to the flutter_blue issue
https://github.com/pauldemarco/flutter_blue/issues/336

**Comment by whatdtech** [comment] 2023-04-10 15:30
https://github.com/boskokg/flutter_blue_plus/issues/225
follow this thread and it clears all your device discovery issues

**Comment by chipweinberger** [comment] 2023-04-27 12:35
closing as dupe of https://github.com/boskokg/flutter_blue_plus/issues/225

**Closed by chipweinberger** 2023-04-27 12:35 UTC
